---
- name: Setup Docker
  hosts: all
  become: true
  tasks:

    - name: Install dependencies
      apt:
        name: "{{ packages }}"
        state: present
        update_cache: true
      vars:
        packages:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - gnupg-agent
